import { fail } from './config.mjs'

export function hasSecret(value) {
  const text = String(value ?? '')
  return (
    /\b(?:gh[pousr]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9_-]{20,}|AKIA[A-Z0-9]{16})\b/.test(
      text,
    ) ||
    /-----BEGIN (?:[A-Z ]+)?PRIVATE KEY-----/.test(text) ||
    [
      ...text.matchAll(
        /\b(?:api[_-]?key|access[_-]?token|GH_TOKEN|password|secret)\s*[:=]\s*["']?([A-Za-z0-9_+/=-]{12,})/gi,
      ),
    ].some(
      (match) =>
        !['YOUR_API_KEY', 'REPLACE_WITH_RANDOM_SECRET', 'PLACEHOLDER_SECRET'].includes(
          match[1].toUpperCase().replaceAll('-', '_'),
        ),
    )
  )
}

export function checkMetadata(...values) {
  const text = values.join('\n')
  if (
    /\b(?:codex|chatgpt|openai|claude|copilot|gemini|anthropic|gpt[- ]?\d|ai[- ]?(?:generated|assisted)|generated by|co-authored-by)\b/i.test(
      text,
    ) ||
    /(?:^|[^a-z])ai(?:$|[^a-z])/i.test(text)
  )
    fail('Metadata Git/GitHub phải trung lập, không có tên công cụ hoặc attribution bị cấm.')
  if (hasSecret(text)) fail('Metadata chứa mẫu secret; không công bố.')
}
export function checkBranch(branch, login, id) {
  checkMetadata(branch)
  if (!branch.startsWith(`feature/${login}/issue-${id}-`) || !/^[a-zA-Z0-9/_-]+$/.test(branch))
    fail('Branch phải theo mẫu feature/<login>/issue-<id>-<slug>.')
}

export function inspectHook(input) {
  const event = input.hook_event_name
  if (event === 'UserPromptSubmit') {
    if (typeof input.prompt !== 'string') return 'Không đọc được prompt; kiểm tra cấu hình hook.'
    return hasSecret(input.prompt)
      ? 'Phát hiện mẫu secret. Không gửi key qua chat; nhập bằng editor vào env local. Nếu là key thật đã chia sẻ, thu hồi và tạo lại.'
      : null
  }
  if (event !== 'PreToolUse') return 'Hook event không được hỗ trợ.'
  const data = input.tool_input
  if (!data || typeof data !== 'object') return 'Không đọc được tool input; kiểm tra cấu hình hook.'
  const text = JSON.stringify(data)
  if (hasSecret(text)) return 'Tool input chứa mẫu secret; dừng thao tác.'
  if (/credential\.mjs/i.test(text))
    return 'Credential helper chỉ được Git gọi qua private protocol; không chạy hoặc in output trực tiếp.'
  if (
    /(?:^|[\s/\\"'])\.env(?:\.[a-zA-Z0-9_-]+)*(?![a-zA-Z0-9_.-])/.test(
      text.replace(/\.env(?:\.workflow)?\.example/g, 'ENV_TEMPLATE'),
    ) ||
    /(?:\.ssh[/\\]|id_rsa|id_ed25519|credentials\.json|auth\.json)/i.test(text)
  )
    return 'Không đọc/ghi credentials trực tiếp bằng tool. Dùng workflow helper; người dùng tự sửa env bằng editor.'
  if (
    /\b(?:printenv|set\s*\||Get-ChildItem\s+Env:|process\.env|os\.environ)\b/i.test(text) ||
    /(?:^|[;&|\s])env\s*(?:[;&|]|$)/.test(data.command ?? data.cmd ?? '')
  )
    return 'Không dump biến môi trường vào output.'
  if (/--no-verify|core\.hooksPath|HUSKY\s*=\s*0|GIT_CONFIG_COUNT/i.test(text))
    return 'Không tắt hoặc đổi hooks trong khi làm ticket.'
  if (/\bgit\b[^\n]*\bpush\b/i.test(text) || /\bgh\s+pr\s+(?:merge|create)\b/i.test(text))
    return 'Dùng task-release và helper publish; không push/merge trực tiếp từ tool.'
  return null
}
